spring.application.name=eventos-api

spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.xvpxeysltqiqivbzalie
spring.datasource.password=@alunoesuda
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.datasource.hikari.keepaliveTime=30000
spring.datasource.hikari.maxLifetime=600000